#!/usr/bin/env python3
"""
FLM -> flash algorithm bin + cfg converter.

Parses a Keil .FLM file (ARM ELF) and produces:
  - <out>.bin : raw Thumb code, to be loaded into target RAM at ram_addr
  - <out>.cfg : text key=value with chip/flash/ram info and function offsets

Usage:
  python3 flm2bin.py input.flm [-o out_base] [-c chip_name] [--ram 0x20000000]

Requires: pip install pyelftools
"""
import argparse
import struct
import sys

from elftools.elf.elffile import ELFFile
from elftools.elf.constants import SH_FLAGS

FUNCS = ["Init", "UnInit", "EraseChip", "EraseSector", "ProgramPage"]

# Keil FlashDevice structure layout (offsets in bytes)
FLASH_DEVICE = {
    "DevType":   130,  # unsigned short
    "DevSize":   132,  # unsigned long  (bytes)
    "PageSize":  136,  # unsigned long
    "EraseValue":140,  # unsigned long
    "ProgBase":  144,  # unsigned long
    "SectorSize":172,  # unsigned long
}


def find_code_seg(elf):
    """Pick the segment holding the flash algorithm code."""
    for seg in elf.iter_segments():
        if seg["p_type"] == "PT_LOAD":
            for sec_idx in seg.sections_iter():
                sec = sec_idx
                name = sec.name
                if name and ("PrgCode" in name or "prg_code" in name):
                    return sec
    # fallback: segment containing the Init symbol
    symtab = elf.get_section_by_name(".symtab")
    if symtab:
        for sym in symtab.iter_symbols():
            if sym.name == "Init":
                for sec in elf.iter_sections():
                    if sec["sh_addr"] <= sym["st_value"] < sec["sh_addr"] + sec["sh_size"] \
                       and sec["sh_type"] == "SHT_PROGBITS":
                        return sec
    return None


def read_elf_data(elf, addr, size):
    """Read raw bytes from the ELF image at virtual address `addr`."""
    for seg in elf.iter_segments():
        if seg["p_type"] != "PT_LOAD":
            continue
        vaddr = seg["p_vaddr"]
        fsize = seg["p_filesz"]
        if vaddr <= addr < vaddr + fsize:
            off = seg["p_offset"] + (addr - vaddr)
            return seg.data()[addr - vaddr: addr - vaddr + size]
    return None


def get_symbols(elf):
    syms = {}
    symtab = elf.get_section_by_name(".symtab")
    if not symtab:
        return syms
    for sym in symtab.iter_symbols():
        if sym["st_info"]["type"] == "STT_FUNC":
            syms[sym.name] = sym["st_value"]
        elif sym.name in ("FlashDevice", "SectorInfo"):
            syms[sym.name] = sym["st_value"]
    return syms


def main():
    ap = argparse.ArgumentParser(description="FLM -> algo bin + cfg")
    ap.add_argument("input", help="input .FLM file")
    ap.add_argument("-o", "--out", default=None, help="output base name (default: input basename)")
    ap.add_argument("-c", "--chip", default="GENERIC", help="chip model name stored in cfg")
    ap.add_argument("--ram", default=None, help="override algorithm RAM base address, e.g. 0x20000000")
    args = ap.parse_args()

    base = args.out or args.input.rsplit(".", 1)[0]

    with open(args.input, "rb") as f:
        elf = ELFFile(f)

        code_sec = find_code_seg(elf)
        if not code_sec:
            sys.exit("error: cannot find code segment (PrgCode) in FLM")

        ram_addr = code_sec["sh_addr"]
        if args.ram:
            ram_addr = int(args.ram, 0)

        bin_data = bytes(code_sec.data())
        syms = get_symbols(elf)

        # function offsets relative to code segment base
        fn = {}
        for name in FUNCS:
            if name in syms:
                fn[name] = syms[name] - code_sec["sh_addr"]
            else:
                fn[name] = 0

        # FlashDevice description
        flash_size = page_size = sector_size = 0
        if "FlashDevice" in syms:
            raw = read_elf_data(elf, syms["FlashDevice"], 176)
            if raw and len(raw) >= 176:
                flash_size = struct.unpack_from("<L", raw, FLASH_DEVICE["DevSize"])[0]
                page_size = struct.unpack_from("<L", raw, FLASH_DEVICE["PageSize"])[0]
                sector_size = struct.unpack_from("<L", raw, FLASH_DEVICE["SectorSize"])[0]
                if sector_size == 0:
                    sector_size = flash_size  # uniform sectors

        name = base.rsplit("/", 1)[-1]

        bin_path = base + "_algo.bin"
        cfg_path = base + ".cfg"
        with open(bin_path, "wb") as bf:
            bf.write(bin_data)

        with open(cfg_path, "w") as cf:
            cf.write("# generated by flm2bin.py\n")
            cf.write("name=%s\n" % name)
            cf.write("chip=%s\n" % args.chip)
            cf.write("flash_size_kb=%d\n" % (flash_size // 1024))
            cf.write("ram_addr=0x%08X\n" % ram_addr)
            cf.write("algo_bin=%s\n" % bin_path.rsplit("/", 1)[-1])
            cf.write("default=0\n")
            for n in FUNCS:
                cf.write("%s=0x%X\n" % (n, fn[n]))
            cf.write("page_size=%d\n" % page_size)
            cf.write("sector_size=%d\n" % sector_size)

        print("code: %d bytes @ 0x%08X" % (len(bin_data), ram_addr))
        print("flash: %d KB, page %d, sector %d" % (flash_size // 1024, page_size, sector_size))
        for n in FUNCS:
            print("  %-12s 0x%X" % (n, fn[n]))
        print("wrote: %s" % bin_path)
        print("wrote: %s" % cfg_path)


if __name__ == "__main__":
    main()
